DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users(
    id INTEGER NOT NULL AUTO_INCREMENT UNIQUE,
    username VARCHAR(256) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    api_key VARCHAR(256) NOT NULL
);
